image: sergiogasquez/esp-rs-env:esp32c3-training

tasks:
  - name: Adopt environment in the container image to gitpod user
    command: |
      ln -s /home/vscode/.rustup /home/gitpod/.rustup
      # mkdir /home/gitpod/.cargo
      ln -s /home/vscode/.cargo/bin /home/gitpod/.cargo/bin
      ln -s /home/vscode/.cargo/env /home/gitpod/.cargo/env
      source /home/gitpod/.cargo/env
      source /home/vscode/export-rust.sh
vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - vadimcn.vscode-lldb
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one