image:
  file: .gitpod.Dockerfile
tasks:
  - name: Setup environment variables for ESP-IDF
    command: |
      source /home/gitpod/.espressif/frameworks/esp-idf/export.sh > /dev/null 2>&1
vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
    - webfreak.debug
    - actboy168.tasks
    - serayuzgur.crates
ports:
  - port: 9012
    visibility: public
