# Choose between building from Dockerfile or pulling the built image.
image: sergiogasquez/esp-rs-env:esp32c3-training
# image:
# Due to https://github.com/gitpod-io/gitpod/issues/7754 building from Dockerfile is not working
#   file: .devcontainer/Dockerfile
tasks:
  - name: Adopt environment in the container image to gitpod user
    command: |
      ln -s /home/esp/.rustup /home/gitpod/.rustup
      mkdir /home/gitpod/.cargo
      ln -s /home/esp/.cargo/bin /home/gitpod/.cargo/bin
      ln -s /home/esp/.cargo/env /home/gitpod/.cargo/env
      source /home/gitpod/.cargo/env
vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - vadimcn.vscode-lldb
    - anwar.resourcemonitor
    - yzhang.markdown-all-in-one
ports:
  - port: 9012
    visibility: public