[package]
name = "host-client"
version = "0.1.0"
edition = "2021"

[dependencies]
rumqttc = "=0.20.0"
rand = "=0.8.5"
toml-cfg = "=0.1.3"
get-uuid = { path = "../../../common/lib/get-uuid" }
mqtt-messages = { path = "../../../common/lib/mqtt-messages" }
