---
name: CI

on:
  push:
    paths-ignore:
      - "book/"
      - "book/**"
  pull_request:
    branches: [main]
    paths-ignore:
      - "book/"
      - "book/**"
  schedule:
    - cron: "50 7 * * *"

jobs:
  build-examples:
    name: Build ${{ matrix.project.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: "button-interrupt"
            path: "advanced/button-interrupt"
          - name: "i2c-driver"
            path: "advanced/i2c-driver"
          - name: "i2c-sensor-reading"
            path: "advanced/i2c-sensor-reading"
          - name: "hardware-check"
            path: "intro/hardware-check"
          - name: "http-client"
            path: "intro/http-client"
          - name: "http-server"
            path: "intro/http-server"
          - name: "mqtt"
            path: "intro/mqtt/exercise"
          - name: "mqtt - host client"
            path: "intro/mqtt/host-client"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build Docker image
        if: github.event_name != 'schedule'
        run: docker image build --tag espressif/rust-std-training --file .devcontainer/Dockerfile .

      - name: Pull Docker image
        if: github.event_name == 'schedule'
        run: docker image pull espressif/rust-std-training

      - name: Test code example in Docker image
        run: |
          docker run -u esp --mount type=bind,source="$(pwd)",target=/home/esp/workspace,consistency=cached \
                 --rm espressif/rust-std-training:latest /bin/bash /home/esp/workspace/.devcontainer/test.sh ${{ matrix.project.path }}
