---
name: CI

on:
  push: {}
  pull_request:
    branches: [main]
    paths-ignore:
      - "book/"
      - "book/**"
  schedule:
    - cron: "50 7 * * *"

jobs:
  # To avoid uploading the Docker image to a registry yet
  # the image is built here & immediately used to test all exercises in.
  build_image_and_test:
    name: Build ${{ matrix.project.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: "button-interrupt"
            path: "advanced/button-interrupt"
          - name: "i2c-driver"
            path: "advanced/i2c-driver"
          - name: "i2c-sensor-reading"
            path: "advanced/i2c-sensor-reading"
          - name: "hardware-check"
            path: "intro/hardware-check"
          - name: "http-client"
            path: "intro/http-client"
          - name: "http-server"
            path: "intro/http-server"
          - name: "mqtt"
            path: "intro/mqtt/exercise"
          - name: "mqtt - host client"
            path: "intro/mqtt/host-client"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker image build --tag esp --file .devcontainer/Dockerfile .

      - name: Test code example in Docker image
        run: |
          docker run --mount type=bind,source="$(pwd)",target=/workspace,consistency=cached \
                 --rm esp:latest /bin/bash /workspace/.devcontainer/test.sh ${{ matrix.project.path }}
